mongodb:
  mongoUri: mongodb://127.0.0.1:27017/product-db
  maxConnections: 20
  connectionTimeoutMillis: 1000
  socketTimeoutMillis: 1000


httpClient:
  maxTotalConnections: 10
  maxConnectionsPerRoute: 10
  connectTimeoutMillis: 10000
  connectRequestTimeoutMillis: 5000
  socketTimeoutMillis: 10000
  connectionTTLMillis: 60000

logging:
  level:
    com.warehouse.retail: DEBUG
    org.springframework.data.mongodb.core: DEBUG
    org.apache.http.impl.conn.PoolingHttpClientConnectionManager: DEBUG
